services:
  - type: web
    name: blazor-weather-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
    healthCheckPath: /WeatherForecast
    numInstances: 1
    port: 10000
